blank_issues_enabled: true
contact_links:
  - name: General Questions
    url: mailto:hello@archipelag.io
    about: For questions that aren't bugs or feature requests
  - name: Documentation
    url: https://docs.archipelag.io
    about: Check the docs for guides and API reference
